name: Build a Docker image and push it to ACR

on:
  push: 
    branches: [main]

  workflow_dispatch:

env:
  TAG: v1
  SERVER: demoblogsiteregistry.azurecr.io
  IMAGE: devops-container

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Test
        run: go test -v ./...

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ env.SERVER }}/${{ env.IMAGE }}:${{ env.TAG }}
          docker push ${{ env.SERVER }}/${{ env.IMAGE }}:${{ env.TAG }}
